import './global.css';
import Home from './components/home';
import React from 'react';

export const metadata = {
  title: 'Welcome to jam-next',
  description: 'Generated by create-nx-workspace'
};

export default function RootLayout({ children }: { children: React.ReactNode; }) {
  return (
    <html lang="en">
    <body><Home>{children}</Home></body>
    </html>
  );
}
